AskPeople.Web/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using AskPeople.BLL.DTO;

namespace AskPeople.Web.ViewModels
{
    public class HomeViewModel
    {
        public List<UserInterviewDTO> UserInterviews { get; set; }
        public List<InterviewInvitationDTO> Invitation { get; set; }
        public List<UserInterviewDTO> SharedForEditing { get; set; }

        public HomeViewModel()
        {
            UserInterviews = new List<UserInterviewDTO>();
            Invitation = new List<InterviewInvitationDTO>();
            SharedForEditing = new List<UserInterviewDTO>();
        }
    }
}

AskPeople.Web/Controllers/HomeController.cs
using AskPeople.BLL.Interfaces;
using AskPeople.Web.Attributes;
using AskPeople.Web.Models;
using AskPeople.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AskPeople.Web.Controllers
{
    [Authentification]
    public class HomeController : Controller
    {
        private readonly HomeModel _homeModel;

        public HomeController(IInterviewService interviewService)
        {
            _homeModel = new HomeModel(interviewService);
        }

        public IActionResult Index()
        {
            string userName = User.Identity.Name;
            HomeViewModel model = new HomeViewModel();
            model.UserInterviews = _homeModel.GetUserVotings(userName);
            model.Invitation = _homeModel.GetInvitations(userName);
            model.SharedForEditing = _homeModel.GetSharedForEditing(userName);
            return View("Index", model);
        }
    }
}

AskPeople.Web/Controllers/InterviewController.cs
using System;
using AskPeople.BLL.Interfaces;
using AskPeople.Web.Attributes;
using AskPeople.Web.Models;
using AskPeople.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AskPeople.Web.Controllers
{
    [CustomExceptionFilter]
    [Authentification]
    public class InterviewController : Controller
    {
        private readonly InterviewModel _interviewModel;

        public InterviewController(IInterviewService interviewService)
        {
            _interviewModel = new InterviewModel(interviewService);
        }

        [HttpGet]
        public IActionResult CreateVoting()
        {
            return View("CreateVoting");
        }

        [HttpPost]
        public IActionResult CreateVoting(VotingViewModel model)
        {
            if (ModelState.IsValid || ModelState.ErrorCount == 1)
            {
                _interviewModel.CreateVoting(model, User.Identity.Name);
                return RedirectToAction("Index", "Home");
            }

            return View("CreateVoting", model);
        }
        
        [HttpGet]
        public IActionResult EditVoting(int id)
        {
            var voting = _interviewModel.GetVotingById(id);
            if (voting == null)
            {
                return NotFound();
            }
            if (voting.User.Nickname != User.Identity.Name && !_interviewModel.AllowedEditing(id, User.Identity.Name))
            {
                throw new Exception();
            }
            
            return View("EditVoting", voting);
        }

        [HttpPost]
        public IActionResult EditVoting(VotingViewModel model)
        {
            if (ModelState.IsValid || ModelState.ErrorCount == 1)
            {
                _interviewModel.EditVoting(model);
                return RedirectToAction("Index", "Home");
            }

            return View("EditVoting", model);
        }

        [HttpPost]
        public IActionResult DeleteVoting(int id)
        {
            _interviewModel.DeleteVoting(id);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Vote(int id)
        {
            var voting = _interviewModel.GetVotingForVote(id, User.Identity.Name);
            if (voting == null)
            {
                throw new Exception();
            }

            return View("MakeVote", voting);
        }

        [HttpPost]
        public IActionResult Vote(MakeVoteViewModel model)
        {
            _interviewModel.MakeVote(model, User.Identity.Name);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ViewResults(int id)
        {
            var model = _interviewModel.GetVotingResults(id, User.Identity.Name);
            if (model == null)
            {
                throw new Exception();
            }
            if (model.Owner != User.Identity.Name && !_interviewModel.AllowedEditing(id, User.Identity.Name))
            {
                throw new Exception();
            }

            return View("VotingResults", model);
        }

    }
}

AskPeople.Web/Views/Home/Index.cshtml
@model AskPeople.Web.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "Home";
}

<div class="col-md-9">
    <div class="interview-panel">
        <div class="user-interview">
            <h3 class="section-headers" align="center">User interview</h3>
            @if (Model.UserInterviews.Count > 0)
            {
                <table class="table">
                    <tr><th>Title</th><th>Description</th><th></th></tr>
                    @foreach (var interview in Model.UserInterviews)
                    {
                        <tr>
                            <td>@interview.Name</td>
                            <td>@interview.Description</td>
                            <td>
                                <form asp-controller="Interview" asp-action="DeleteVoting" asp-route-id="@interview.Id" method="post">
                                    @if (interview.IsPublished)
                                    {
                                        <a class="btn btn-sm btn-primary" asp-controller="Interview" asp-action="ViewResults" asp-route-id="@interview.Id">Results</a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-sm btn-primary" asp-controller="Interview" asp-action="EditVoting" asp-route-id="@interview.Id">Edit</a>
                                    }
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>There are no elements!</p>
            }
        </div>
        <div class="interview-invitations">
            <h3 class="section-headers" align="center">Invitations</h3>
            @if (Model.Invitation.Count > 0)
            {
                <table class="table">
                    <tr><th>Title</th><th>Description</th><th>By</th><th></th></tr>
                    @foreach (var interview in Model.Invitation)
                    {
                        <tr>
                            <td>@interview.Title</td>
                            <td>@interview.Description</td>
                            <td>@interview.Owner</td>
                            <td>
                                @if (!interview.IsVoted)
                                {
                                    <a class="btn btn-sm btn-primary" asp-controller="Interview" asp-action="Vote" asp-route-id="@interview.Id">Vote</a>
                                }
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>There are no elements!</p>
            }
        </div>
        <div class="shared-for-editing">
            <h3 class="section-headers" align="center">Shared for editing</h3>
            @if (Model.SharedForEditing.Count > 0)
            {
                <table class="table">
                    <tr><th>Title</th><th>Description</th><th>Author</th><th></th></tr>
                    @foreach (var interview in Model.SharedForEditing)
                    {
                        if (!interview.IsPublished)
                        {
                             <tr>
                                 <td>@interview.Name</td>
                                 <td>@interview.Description</td>
                                 <td>@interview.Owner</td>
                                 <td>
                                     <a class="btn btn-sm btn-primary" asp-controller="Interview" asp-action="EditVoting" asp-route-id="@interview.Id">Edit</a>
                                 </td>
                             </tr>
                        }
                    }
                </table>
            }
            else
            {
                <p>There are no elements!</p>
            }
        </div>
    </div>
</div>
<div class="col-md-3 right-panel">
    <div class="creation-panel">
        <h3 class="section-headers" align="center">Create new interview</h3>
        <div>
            <a class="btn btn-primary creation-btn" asp-controller="Interview" asp-action="CreateVoting" role="button">New voting</a>
            <a class="btn btn-primary creation-btn" href="#" role="button">New questionaire</a>
        </div>
    </div>
</div>