AskPeople.Web/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AskPeople.Web.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Nickname { get; set; }

        [Required]
        public string Password { get; set; }
        
        [Display(Name = "Remember?")]
        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

AskPeople.Web/Controllers/AuthentificationController.cs
using System;
using AskPeople.BLL.Interfaces;
using AskPeople.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AskPeople.Web.Models;

namespace AskPeople.Web.Controllers
{
    public class AuthentificationController : Controller
    {
        private readonly AuthentificationModel _authentificationModel;

        public AuthentificationController(IAuthenticationService authenticationService)
        {
            _authentificationModel = new AuthentificationModel(authenticationService);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View("Registration");
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationModel model)
        {
            if (ModelState.IsValid)
            {

                var errors = await _authentificationModel.ValidateAndRegister(model);
                if (errors == null || errors.Count == 0)
                {
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }

            return View("Registration", model);
        }

        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            return View("Login", new LoginViewModel{ReturnUrl = returnUrl});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var errors = await _authentificationModel.SignInUser(model);
                if (errors == null || errors.Count == 0)
                {
                    if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }

                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in errors)
                {
                    ModelState.AddModelError(String.Empty, error);
                }
            }

            return View("Login", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await _authentificationModel.SignOutUser();

            return RedirectToAction("Index", "Home");
        }
    }
}

AskPeople.Web/Views/Authentification/Login.cshtml
@model AskPeople.Web.ViewModels.LoginViewModel
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/mystyles.css">

    <title>Welcome</title>
</head>
<body>
    <div class="container col-md-5 register-main">
        <div class="container col-md-7">
            <div class="register-logo"><h2>Welcome to <b>AskPeople</b> </h2></div>
            <form id="loginForm" method="post">
                <div class="form-group">
                    <label asp-for="Nickname">Nickname</label>
                    <input asp-for="Nickname" type="text" class="form-control" id="nickname" placeholder="Enter nickname">
                    <span asp-validation-for="Nickname" id="nickname-validation" class="validate-warning"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password">Password</label>
                    <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password">
                    <span asp-validation-for="Password" id="password-validation" class="validate-warning"></span>
                </div>
                <div>
                    <label asp-for="RememberMe"></label>
                    <input asp-for="RememberMe" />
                </div>
                <div>
                    <a asp-controller="Authentification" asp-action="Register">Registration</a>
                </div>
                <div asp-validation-summary="ModelOnly"></div>
                <div class="text-center register-sub-btn">
                    <input type="submit" class="btn btn-primary col-md-5" onClick="validateLoginView()" value="Log In" />
                </div>
            </form>
        </div>
    </div>
    
    <script src="~/js/validation.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>


</body>
</html>

AskPeople.Web/Views/Authentification/Registration.cshtml
@model AskPeople.Web.ViewModels.RegistrationModel
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/mystyles.css">
    
    <title>Welcome</title>
</head>
<body>
    <div class="container col-md-5 register-main">
        <div class="container col-md-7">
            <div class="register-logo"><h2>Welcome to <b>AskPeople</b> </h2></div>
            <form id="registerForm" method="post">
                <div class="form-group">
                    <label asp-for="Email">Email address</label>
                    <input asp-for="Email" type="email" class="form-control" id="email" placeholder="Enter email">
                    <span asp-validation-for="Email" id="email-validation" class="validate-warning"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nickname">Nickname</label>
                    <input asp-for="Nickname" type="text" class="form-control" id="nickname" placeholder="Enter nickname">
                    <span asp-validation-for="Nickname" id="nickname-validation" class="validate-warning"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password">Password</label>
                    <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password">
                    <span asp-validation-for="Password" id="password-validation" class="validate-warning"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password2">Repeat password</label>
                    <input asp-for="Password2" type="password" class="form-control" id="password2" placeholder="Password">
                    <span asp-validation-for="Password2"></span>
                </div>
                <div>
                    <label asp-for="Tags">Tags</label>
                    <small id="tagsHelp" class="text-muted">Input tags divided by space. Tag should start with '#' symbol!</small>
                    <textarea asp-for="Tags" class="form-control" name="tags" id="tags" rows="3" aria-describedby="tagsHelp" placeholder="#tag1 #tag2 ..."></textarea>
                    <span asp-validation-for="Tags"></span>
                </div>
                <div asp-validation-summary="ModelOnly"></div>
                <div class="text-center register-sub-btn">
                    <input type="submit" onClick="validateRegisterView()" class="btn btn-primary col-md-5" value="Register"/>
                </div>
            </form>
        </div>
    </div>

<script src="~/js/validation.js"></script>  
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>